# Generated by Django 4.2.2 on 2023-06-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ab', '0003_useraccount_adress_useraccount_brand_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
