# Generated by Django 4.1 on 2024-02-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ab', '0004_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_abssence', models.CharField(blank=True, max_length=10000, null=True)),
                ('decision_abssence', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_degree', models.CharField(blank=True, max_length=10000, null=True)),
                ('nombre_de_echlon', models.CharField(blank=True, max_length=10000, null=True)),
                ('date_avencement', models.CharField(blank=True, max_length=10000, null=True)),
                ('id_avencement_personel', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(blank=True, max_length=10000, null=True)),
                ('nom', models.CharField(blank=True, max_length=10000, null=True)),
                ('sex', models.CharField(blank=True, max_length=10000, null=True)),
                ('adress', models.CharField(blank=True, max_length=10000, null=True)),
                ('naissance', models.CharField(blank=True, max_length=10000, null=True)),
                ('entre', models.CharField(blank=True, max_length=10000, null=True)),
                ('enfant', models.CharField(blank=True, max_length=10000, null=True)),
                ('prenom_femme', models.CharField(blank=True, max_length=10000, null=True)),
                ('prenom_pere', models.CharField(blank=True, max_length=10000, null=True)),
                ('nom_mere', models.CharField(blank=True, max_length=10000, null=True)),
                ('prenom_mere', models.CharField(blank=True, max_length=10000, null=True)),
                ('tel', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Randement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_rendement', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sanction', models.CharField(blank=True, max_length=10000, null=True)),
                ('duree_sanction', models.CharField(blank=True, max_length=10000, null=True)),
                ('type_sanction', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='NewsLetter',
            new_name='Conge',
        ),
        migrations.DeleteModel(
            name='ContactForm',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.RenameField(
            model_name='conge',
            old_name='date',
            new_name='date_debut',
        ),
        migrations.RenameField(
            model_name='conge',
            old_name='email',
            new_name='duree_fin',
        ),
        migrations.RenameField(
            model_name='conge',
            old_name='time',
            new_name='type_conge',
        ),
    ]
